This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./Bachelorarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Bachelorarbeit.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file Bachelorarbeit.acr....done (6 lines written, 0 warnings).
Output written in Bachelorarbeit.acr.
Transcript written in Bachelorarbeit.alg.
